/* 检索并拼接sql语句，复制所有结果删除所有外键 */
SELECT CONCAT('ALTER TABLE ',TABLE_SCHEMA,'.',TABLE_NAME,' DROP FOREIGN KEY ',CONSTRAINT_NAME,';')
FROM information_schema.TABLE_CONSTRAINTS c
WHERE c.TABLE_SCHEMA='eladmin' AND c.CONSTRAINT_TYPE='FOREIGN KEY';

