name: Maven Build

on:
  push:
    branches: 
      - '*'         # This runs on all branches for the build job
      - 'master'    # Explicitly include master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Make Maven wrapper executable
      run: chmod +x ./mvnw
    
    - name: Build with Maven
      run: ./mvnw clean package -DskipTests

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build

    steps:
    - uses: actions/checkout@v3
    
    - name: Install sshpass
      run: sudo apt-get install -y sshpass
    
    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 172.235.32.135 >> ~/.ssh/known_hosts
        
    - name: Deploy to server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        # Using -o options to handle first-time connection and avoid strict host checking
        export SSHPASS="$SSH_PASSWORD"
        sshpass -e ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@172.235.32.135 "cd backend && \
        pkill -f 'java -jar' || true && \
        git pull && \
        ./mvnw clean package && \
        nohup java -jar eladmin-system/target/eladmin-system-2.7.jar > app.log 2>&1 &"
